<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../package/package_desktop/dotnet/Interop.cs" Link="Kernel/Interop.cs" />
    <Compile Include="../../package/package_desktop/dotnet/ArupaBrowser.cs" Link="Kernel/ArupaBrowser.cs" />
  </ItemGroup>
</Project>
