#!/usr/bin/env python3
"""从单一来源 arupa_plugin_registry.json 生成内核 C++ 注册表头 arupa_plugin_registry.h。

设计：内核的「宿主/内核路由前缀、宿主事件、协议插件命名空间」不再散写在 C++
表里，而是由本文件登记的 JSON 派生；生成的 .h 被 arupa_ext_api_prefixes.h 直接
include（C++ 侧不再手写这三张表），scripts/kernel_capability.py 也从同一份 JSON
派生门禁事实。改登记表后重跑本脚本即可（生成结果是检入库的康复产物）。

用法：
    python3 scripts/gen_arupa_plugin_registry.py [--check]
不带 --check：读取 JSON 并覆盖写 arupa_plugin_registry.h。
带  --check：只校验生成头与 JSON 一致（不一致则 exit 1），不写文件。
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
SRC = WORKSPACE_ROOT / "src"
REGISTRY = SRC / "chrome/browser/arupa_android/plugin/arupa_plugin_registry.json"
HEADER = SRC / "chrome/browser/arupa_android/plugin/arupa_plugin_registry.h"

HEADER_TEMPLATE = """// AUTO-GENERATED by scripts/gen_arupa_plugin_registry.py.
// 数据来源: chrome/browser/arupa_android/plugin/arupa_plugin_registry.json。
// 不要手改本文件 —— 改登记表后重跑生成器（npm 之外的编前动作）。门禁
// scripts/kernel_capability.py 会校验本生成头与 JSON 是否同源，不一致直接拒绝出包。
#ifndef CHROME_BROWSER_ARUPA_PLUGIN_ARUPA_PLUGIN_REGISTRY_H_
#define CHROME_BROWSER_ARUPA_PLUGIN_ARUPA_PLUGIN_REGISTRY_H_

#include <string_view>

namespace arupa {{

// 由 arupa_plugin_registry.json / routing / host_owned_prefixes 派生。
// 宿主拥有的 API 前缀：命中的方法一律转给宿主(kHost)处理。
inline constexpr std::string_view kHostOwnedPrefixes[] = {{
{host_owned}
}};

// 由 routing / kernel_owned_bridge_prefixes 派生。内核直接实现的桥接入口。
inline constexpr std::string_view kKernelOwnedBridgePrefixes[] = {{
{kernel_owned}
}};

// 由 routing / host_fireable_events 派生。宿主(fireExtEvent)允许主动发的事件白名单。
inline constexpr std::string_view kHostFireableEvents[] = {{
{host_fireable}
}};

// 由 protocol_plugins 派生：每个可登记的协议插件命名空间(裸名，不带尾点)。
inline constexpr std::string_view kArupaProtocolNamespaces[] = {{
{proto_namespaces}
}};

// 由 protocol_plugins 派生：每个命名空间的名常量(k{{Name}}Namespace)，供
// RegisterPermissions / AddAPIFeatures 等处引用，避免在 C++ 里散写字符串字面量。
{proto_consts}
}}  // namespace arupa

#endif  // CHROME_BROWSER_ARUPA_PLUGIN_ARUPA_PLUGIN_REGISTRY_H_
"""


def _to_string_literals(items: list) -> str:
    # 每行一条（带尾逗号），最后一条的尾逗号在 C++ 初始化列表里合法。
    return "\n".join('    "{}",'.format(i) for i in items)


def _camel(ns: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", ns)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def generate(registry: dict) -> str:
    routing = registry["routing"]
    protos = registry["protocol_plugins"]
    const_lines = []
    for p in protos:
        name = p["namespace"]
        const_lines.append(
            f'inline constexpr std::string_view k{_camel(name)}Namespace = "{name}";')
    return HEADER_TEMPLATE.format(
        host_owned=_to_string_literals(routing["host_owned_prefixes"]),
        kernel_owned=_to_string_literals(routing["kernel_owned_bridge_prefixes"]),
        host_fireable=_to_string_literals(routing["host_fireable_events"]),
        proto_namespaces=_to_string_literals([p["namespace"] for p in protos]),
        proto_consts="\n".join(const_lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="只校验生成头与 JSON 一致，不写文件")
    args = ap.parse_args()

    if not REGISTRY.is_file():
        print(f"[ERROR] 缺单一来源登记表: {REGISTRY}", file=sys.stderr)
        return 1
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    wanted = generate(data)

    if args.check:
        if not HEADER.is_file():
            print(f"[ERROR] 缺生成头: {HEADER}（尚无生成产物）", file=sys.stderr)
            return 1
        current = HEADER.read_text(encoding="utf-8")
        if current != wanted:
            print(f"[ERROR] 生成头与登记表不同源: {HEADER}", file=sys.stderr)
            print("[HINT] 重跑 python3 scripts/gen_arupa_plugin_registry.py", file=sys.stderr)
            return 1
        print(f"[OK] 生成头与登记表同源: {HEADER}")
        return 0

    HEADER.write_text(wanted, encoding="utf-8")
    print(f"[OK] 已生成: {HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())